### ISSUE TITLE
[Requirement] Gruppenchat

### ISSUE THREAD

**Issue by ghost** [twittwer/ase16#12]
## Szenario: Gruppenchat beitreten als unbekannter Anwender

Die Anwendung kennt als Anwender mich noch nicht
WENN ich die Anwendung öffne
UND ich einen Nickname eingebe
UND diesen bestätige
DANN öffnet sich mir der Gruppenchat
UND ich bin dort unter meinem Nickname zu erkennen.
## Szenario2: Gruppenchat beitreten als bekannter Anwender

Die Anwendung kennt meinen Nickname noch.
WENN ich die Anwendung öffne
DANN öffnet sich mir direkt der Gruppenchat 
UND ich bin dort unter meinem Nickname zu erkennen.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by twittwer** [comment]
@akramer-dozent Es ist ein Gruppenchat für alle User gemeint, richtig?

**Comment by ghost** [comment]
@twittwer ja. Ein Gruppenchat für alle User.

**Comment by twittwer** [comment]
Closed by 1ef5e43
