### ISSUE TITLE
[Requirement] Voting-Optionen

### ISSUE THREAD

**Issue by ghost** [twittwer/ase16#14]
## Szenario: Neue Option anlegen

Ich bin im Gruppenchat
WENN ich auf "Option anlegen" klicke
DANN erhalte ich eine Eingabemaske
UND kann dort eine "Bezeichnung" eintragen
UND bei Bestätigung wird eine neue Option angelegt.
## Szenario2: Option löschen

Ich bin im Gruppenchat
UND ich bin diejenige Person die eine Option angelegt hat
WENN ich auf "Option löschen" klicke
DANN wird die entsprechende Voting Option gelöscht.
## Szenario3: Keine Berechtigung Option zu löschen

Ich bin im Gruppenchat
UND es gibt Voting-Optionen die nicht von mir stammen
DANN kann ich diese nicht löschen.

Diese Anforderung ist (1 \* count(Teammitglieder)) Punkte für die Gruppe wert. 
Alle oben genannten Akzeptanzkriterien müssen erfolgreich erfüllt 
sein, um die Punkte zu bekommen.

**Comment by twittwer** [comment]
Szenario 1 & 3 fertig
