### ISSUE TITLE
Project Topic

### ISSUE THREAD

**Issue by BullFrog01** [twittwer/ase16#2]
- ~~Sternenbilder / Sateliten~~
- Notes Application***
  - Simple Notes
  - Note Categories
  - Lists (with progress bar)
  - Note Sharing
- ~~Dualis**~~
  - ~~User Management~~
  - ~~Grade Management~~
  - ~~Statistics~~
- ~~Online Shop~~
- Chat***
  - Simple Chat
  - Group Chat
  - Topic Voting
- ~~Student Application~~
- ~~Places Application~~
  - ~~POI Map~~
  - ~~POI Rating~~
- ~~Diary**~~

**Comment by twittwer** [comment]
Notes Application

**Comment by twittwer** [comment]
Chat

**Comment by twittwer** [comment]
The discussion ended up with the decision to develop a Chat Application.
