### ISSUE TITLE
Installationsprobleme

### ISSUE THREAD

**Issue by ghost** [twittwer/ase16#27]
Ich komm leider nicht weiter als die Login-Maske...

Die Installation der docker container mit docker-compose hat funktioniert. 

hosts-Datei hab ich angepasst. http://local als auch http://api.local sind erreichbar

npm install für backend und frontend haben fehlerfrei funktioniert.

Habt ihr eine Idee woran es liegt? Hab ich bei der Installation etwas vergessen?

**Comment by ghost** [comment]
<img width="960" alt="login" src="https://cloud.githubusercontent.com/assets/17781068/19699938/87f71c82-9af5-11e6-8595-bc747513dac3.PNG">

**Comment by ghost** [comment]
←[35mbackend     | ←[0m[1] registerDBUser
←[35mbackend     | ←[0m[1] registerDBUser
←[35mbackend     | ←[0m[1] registerDBUser
←[35mbackend     | ←[0m[1] registerDBUser

...erscheint im Server-Log, wenn ich auf Login klicke. Es passiert aber nichts.

**Comment by twittwer** [comment]
Kannst du in den Server Logs sehen, ob MongoDB ordentlich gestartet ist.
Es klingt so als fehle die DB Anbindung.

**Comment by ghost** [comment]
backend     | [0] 8:38:21 AM - Compilation complete. Watching for file changes.
backend     | [1] [nodemon] starting `node build/`
backend     | [1] Backend-App is listing on port 4000!
backend     | [1] Mongoose disconnected from mongodb://mongodb/app
backend     | [1] Mongoose connection error: MongoError: failed to connect to server [mongodb:27017] on first connect
frontend    | [1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...

Du hast mit deiner Vermutung sehr wahrscheinlich ins Schwarze getroffen. Bevor wir jetzt aber auf Fehlersuche gehen, lassen wir es und wir werden es am nächsten Termin an einem eurer Rechner anschauen.
