### ISSUE TITLE
Angular2 Unit-Testing mit Karma und Jasmine 

### ISSUE THREAD

**Issue by ghost** [twittwer/ase16#29]
Vielleicht bekommt ihr es mit dem WebStorm zum Laufen. 

Hier die Anleitungen dazu von JetBrains:
https://www.jetbrains.com/help/webstorm/2016.3/preparing-to-use-karma-test-runner.html
https://www.jetbrains.com/help/webstorm/2016.3/running-unit-tests-on-karma.html

**Comment by ghost** [comment]
/**
Kurze Video Tutorials:
Unit Testing AngularJS Lesson 2 Setting Up Karma 
https://www.youtube.com/watch?v=mkyXt0PMBMM

Unit Testing AngularJS Lesson 3 Your First Unit Test 
https://www.youtube.com/watch?v=M0qOKzN6l9o
**/

**Comment by ghost** [comment]
Kleines vielversprechendes Howto 
https://www.agvision.ro/angular-2-unit-testing-karma-jasmine/

**Comment by twittwer** [comment]
Fixed by porting to Angular CLI
